name: Sabre
main: com.gordonfreemanq.sabre.SabrePlugin
version: 0.1.12
description: Sabre plugin
author: GFQ
depend: [PermissionsEx, CombatTagPlus, ProtocolLib, PacketWrapper, VanishNoPacket]
commands:
  faction:
    description: The Faction base command
    aliases: [f]
  msg:
    description: Sends a player a message.
    usage: /<command> <player> <message>
    aliases: [message, tell, m, pm, w]
  reply:
    description: Reply to the last player who was messaged
    usage: /<command> <message>
    aliases: r
  chat:
    description: Sets the chat channel
    usage: /<command> <group>
    aliases: c
  me:
    description: Sends a me message
    usage: /<command> <message>
  help:
    description: Gets plugin help
    usage: /<command>
    aliases: "?"
  unknown:
    description: Unknown commands
    usage: /<command>
    aliases: [ban, parson, give]
  bdi:
    description: Get block information
    usage: /<command>
    aliases: [cti]
  bdf:
    description: Build reinforced blocks
    usage: /<command> <group>
    aliases: [ctf]
  bdr:
    description: Reinforces existing blocks
    usage: /<command> <group>
    aliases: [ctr]
  bdo:
    description: Turns off building
    usage: /<command>
    aliases: [cto]
  bdb:
    description: Toggles bypass mode
    usage: /<command>
    aliases: [ctb]
  sn:
  pp:
  factory:
  speed:
  tp:
  tphere:
  say:
  vanish:
  fly:
  gamemode:
  gm:
  respawn:
  mute:
  ignore:
   
